variables:
  ADVERTISED_HOST: 'spotify__kafka'
  ADVERTISED_PORT: '9092'
  AUTO_CREATE_TOPICS: 'true'
  POSTGRES_HOST_AUTH_METHOD: 'trust'

stages:
  - test

services:
  - spotify/kafka
  - postgres:latest

cache:
  key: "$CI_PROJECT_NAME"
  paths:
    - $HOME/.cache/pip

test:
  stage: test
  image: $IMAGE
  script:
    - pip install tox
    - tox -e $TOX_ENVS
  parallel:
    matrix:
      - IMAGE: python:3.7
        TOX_ENVS: py37-django{220,300,310}-drf{310,311,312}

      - IMAGE: python:3.8
        TOX_ENVS: py38-django{220,300,310}-drf{310,311,312}

      - IMAGE: python:3.9
        TOX_ENVS: py39-django{220,300,310}-drf{310,311,312}

      - IMAGE: pypy:3
        TOX_ENVS: pypy3-django{220,300,310}-drf{310,311,312}
